risc-v/mpfs: emmcsd: enforce HS SDR mode properly
tiiuae/nuttx pull request #101
Opened 2023-04-14 06:13 UTC by jpaali

Previously, address 0x03b70000u was written with shift bits that only changed the bit width, not the mode. Enforce HS SDR mode (50 MHz) for now.

2023-04-14 08:02 UTC, jlaitine approved these changes

2023-04-14 08:57 UTC, jnippula commented
Is it really necessary to use SDR mode? Why would DDR not work?

2023-04-14 09:01 UTC, jlaitine requested changes
Changed my mind; I don't think that we should by default change the mode to SDR; this just changes the timings but can't be the source of the problem.

So this PR should be modified in the way that it fixes the issues related to the mode change, but keeps the mode in DDR

2023-04-14 10:25 UTC, eenurkka commented
> Is it really necessary to use SDR mode? Why would DDR not work?

By default, it's at the Legacy mode, not DDR. Nothing changes it to DDR (nor previously did). One problem is that the legacy mode is for 0-26MHz, but clk is at 50 Mhz, which should be HS mode.

"Variable clock frequencies of 0-20 MHz, 0-26 MHz (default), 0-52 MHz (high-speed), 0-200 MHz SDR (HS200), 0-200 MHz DDR (HS400)"

2023-04-14 11:20 UTC, eenurkka commented
Previously:  

1. Set DDR:
if ((ret = mpfs_sendcmd(dev, MMCSD_CMD6, 0x03b70000u | (6 << 8))) == OK)

2. Unset DDR and use 8-bit lanes:
if ((ret = mpfs_sendcmd(dev, MMCSD_CMD6, 0x03b70000u | (2 << 8))) == OK)
(see: Conversely, a card in the dual data mode may be switched back to single data rate mode by writing new values in the BUS_WIDTH byte.)

I think all reference codes also switch to HS-mode first; DDRs may be used while keeping in mind some modes require PHY tuning.

From Jedec specs:

HS_TIMING must be set to “0x1” before setting BUS_WIDTH for dual data rate operation (values 5 or 6)

After the host verifies that the card complies with version 4.0, or higher, of this standard, it has to enable the high speed mode timing in the card, before changing the clock frequency to a frequency higher than 20MHz. After power-on, or software reset, the interface timing of the card is set as specified in Table 114 on page 177. For the host to change to a higher clock frequency, it has to enable the high speed interface timing.
The host uses the SWITCH command to write 0x01 to the HS_TIMING byte, in the Modes segment of the EXT_CSD register. 

For the host to change to dual data rate mode, HS_TIMING must be set to 0x1 (Section 7.6.2 on page 50) and the card shall supports this mode as defined in EXT_CSD register [196] (CARD_TYPE) specified in Table 84 on page 139. **The host uses the SWITCH command to write 0x05 (4-bit data width) or 0x06 (8-bit data width)** to the BUS_WIDTH byte, in the Modes segment of the EXT_CSD register byte [183]. The valid values for this
register are defined in "BUS_WIDTH" on page 141. If the host tries to write an invalid value, the BUS_WIDTH byte is not changed, the dual data rate mode is not enabled, and the SWITCH_ERROR bit is set. **Conversely, a card in the dual data mode may be switched back to single data rate mode by writing new values in the BUS_WIDTH byte.**

A.8.2 Switching to high-speed mode
The following steps are supported by cards implementing version 4.0 or higher. Do these steps after the bus is initialized according to section Annex A.8.1 on page 203.
22-Send CMD7 with the card’s RCA to place the card in tran state
23-Send CMD8, SEND_EXT_CSD. From the EXT_CSD the host can learn the power class of the card, and choose to work with a wider data bus (See steps 26-37)
24-Send **CMD6, writing 0x1 to the HS_TIMING byte of the EXT_CSD. The argument 0x03B9_0100 will do it.**

2023-04-26 06:24 UTC, jlaitine commented
I guess then setting the SDR mode like in this is more proper, and also the HS mode bit should be set. I wonder how much work would it be to support DDR50 ? IMHO, it shouldn't require training any more than SDR50.

2023-04-26 10:08 UTC, eenurkka commented
I think it's very simple, IIRC, just
 if ((ret = mpfs_sendcmd(dev, MMCSD_CMD6, 0x03b90100u)) == OK)
->
 if ((ret = mpfs_sendcmd(dev, MMCSD_CMD6, 0x03b90600u)) == OK)

2024-11-01 07:50 UTC, jpaali commented
is this still valid? Cannot remember anymore? :smile:

2024-11-01 08:00 UTC, eenurkka commented
No, this is no longer valid; I think a little bit different patch was applied that did the same thing.

2024-11-01 08:01 UTC, eenurkka commented
https://github.com/tiiuae/nuttx/commit/88387591ab97d989ea70c3d7b00a49e2982a1b42

2025-03-03 07:08 UTC, closed without merging